name: frontend
description: "A new Flutter project."
publish_to: 'none' # Avoid publishing to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.3.0
  async: ^2.12.0  # Downgraded to resolve conflict with flutter_test
  material_color_utilities: ^0.11.1  # Fixed version to resolve pinning conflict with flutter_test
  lucide_icons: ^0.257.0
  google_maps_flutter: ^2.6.0
  geolocator: ^14.0.0
  permission_handler: ^12.0.0+1
  image_picker: ^1.0.4
  shared_preferences: ^2.2.2
  flutter_map: ^8.1.1
  latlong2: 0.9.1
  image: ^4.0.17
  flutter_rating_bar: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0  # Downgraded to avoid conflict with version 6.0.0
  fake_async: ^1.3.2  # Pinned to match the version required by flutter_test
  leak_tracker: 10.0.8  # Pinning to 10.0.8 to resolve version conflict
  lints: ^5.1.1  # Keep it in 5.x.x to avoid issues with version 6.0.0
  vm_service: 14.3.1  # Compatible with flutter_test, avoid conflict

flutter:
  uses-material-design: true
  assets:
    - assets/